 // This file has been generated by Specta. DO NOT EDIT.

export type Controller = { name: string; controller_path: string }

export type Dashboard = { name: string; description: string; id: string; file_path: string; data_sources: DataSource[]; controllers: Controller[]; visualizations: Visualization[]; pages: Page[] }

export type DataSource = { name: string; db_url: string; db_password: string }

export type Page = { name: string }

export type TauRpcAppApiInputTypes = { proc_name: "hello_worldorini"; input_type: null } | { proc_name: "get_dashboards"; input_type: null } | { proc_name: "create_dashboard"; input_type: [Dashboard, string] }

export type TauRpcAppApiOutputTypes = { proc_name: "hello_worldorini"; output_type: string } | { proc_name: "get_dashboards"; output_type: Dashboard[] } | { proc_name: "create_dashboard"; output_type: null }

export type TauRpcEventsInputTypes = { proc_name: "test_ev"; input_type: null } | { proc_name: "state_changed"; input_type: { __taurpc_type: string } } | { proc_name: "vec_test"; input_type: { __taurpc_type: string[] } } | { proc_name: "multiple_args"; input_type: [number, string[]] }

export type TauRpcEventsOutputTypes = { proc_name: "test_ev"; output_type: null } | { proc_name: "state_changed"; output_type: null } | { proc_name: "vec_test"; output_type: null } | { proc_name: "multiple_args"; output_type: null }

export type Visualization = { name: string; viz_path: string }

const ARGS_MAP = {"api":"{\"hello_worldorini\":[],\"get_dashboards\":[],\"create_dashboard\":[\"dashboard\",\"dashboard_name\"]}","events":"{\"vec_test\":[\"args\"],\"test_ev\":[],\"multiple_args\":[\"arg1\",\"arg2\"],\"state_changed\":[\"new_state\"]}"}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'api': [TauRpcAppApiInputTypes, TauRpcAppApiOutputTypes],
	'events': [TauRpcEventsInputTypes, TauRpcEventsOutputTypes],
}