[package]
name = "taurpc"
authors = ["MatsDK"]
version = "0.2.6"
edition = "2021"
description = "A type-safe IPC layer for tauri commands"
documentation = "https://docs.rs/taurpc"
homepage = "https://github.com/MatsDK/TauRPC"
repository = "https://github.com/MatsDK/TauRPC"
license = "MIT OR Apache-2.0"
readme = "../README.md"
categories = ["tauri"]
rust = "1.71"

[workspace]
members = [
  "taurpc-macros",
]

[dependencies]
taurpc-macros = { path = "./taurpc-macros", version = "=0.2.6" }

specta = { version = "=2.0.0-rc.9", features = ["export", "typescript"] }
tauri = { version = "1.3" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
